[phases.setup]
nixPkgs = ["python3", "gcc", "python3.pkgs.pip", "python3.pkgs.setuptools", "python3.pkgs.wheel"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install -r requirements.txt",
  "playwright install --with-deps chromium"
]

[start]
cmd = "gunicorn api:app --bind 0.0.0.0:$PORT"
